name: "release"
on: ["push"]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

    - name: deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: main
        folder: build
